---
version: "3.9"
services:
  app:
    image: websurfx:latest
    build: .
    ports:
      - 8080:8080
    depends_on:
      - redis
    links:
      - redis
    volumes:
      - ./websurfx/:/etc/xdg/websurfx/
      - ./public/:/opt/websurfx/public/
  redis:
    image: redis:latest
    ports:
      - 6379:6379
